const COMMANDS = {
    GAME_CREATE: '@KAL/GAME_CREATE',
    PLAYER_CONNECT: '@KAL/PLAYER_CONNECT',
    ROOM_CREATED: '@KAL/ROOM_CREATED',
    PLAYER_JOIN: '@KAL/PLAYER_JOIN',
    SET_USERNAME: '@KAL/SET_USERNAME',
    ROOM_EXPIRED: '@KAL/ROOM_EXPIRED',
    ROOM_JOINED: '@KAL/ROOM_JOINED',
    ROOM_RECONNECT: '@KAL/ROOM_RECONNECT',
    UPDATE_PLAYERS: '@KAL/UPDATE_PLAYERS',
    PLAYER_DISCONNECT: '@KAL/PLAYER_DISCONNECT',
    GAME_OVER: '@KAL/GAME_OVER',
}

module.exports = {
    COMMANDS
};